# to be filed with sql script

CREATE TABLE IF NOT EXISTS LISTING(
    ID INT NOT NULL,
    URL VARCHAR(500) NOT NULL,
    DESCRIPTION TEXT,
    NUMBER_OF_ROOMS INT,
    TOTAL_AREA DECIMAL(3, 1),
    FLOOR INT,
    CREATED_AT DATETIME NOT NULL,
    LAST_CHECKED_AT DATETIME,
    ORIGINAL_PRICE INT NOT NULL,
    SOURCE_WEBSITE VARCHAR(100),

    PRIMARY KEY (ID)
);