CREATE TABLE IF NOT EXISTS SCRAPPING_ERROR(
    ID INT NOT NULL,
    LISTING_ID INT NOT NULL,
    ERROR_MESSAGE TEXT,
    NOTIFY_ON_PRICE_CHANGE TINYINT,
    NOTIFY_ON_AVAILABILITY_CHANGE TINYINT,
    OCCURRED_AT DATETIME,

    PRIMARY KEY (ID),
    FOREIGN KEY (LISTING_ID) references LISTING(ID)
);