
CREATE TABLE IF NOT EXISTS PRICE_HISTORY(
    ID INT NOT NULL,
    LISTING_ID INT NOT NULL,
    PRICE INT,
    RECORDED_AT DATETIME,

    PRIMARY KEY (ID),
    FOREIGN KEY (LISTING_ID) references LISTING(ID)
);